server.port: 7002

spring.datasource:
  url: jdbc:postgresql://localhost/product-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

spring.sql.init:
  mode: always
  schema-locations: classpath:db/init/init.sql
  platform: postgres

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/product-db