server.port: 7002

spring.datasource:
  url: jdbc:postgresql://localhost/product-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

spring:
  liquibase:
    change-log: db/changelog/2025/07/25-01-changelog.yaml

---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/product-db