server.port: 7004

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd

spring.datasource.hikari.initializationFailTimeout: 60000

spring.sql.init:
  mode: always
  schema-locations: classpath:db/init/init.sql
  platform: mysql

spring.jpa:
  hibernate:
    ddl-auto: none
  show-sql: true

logging:
  level:
    org.springframework.web.*: DEBUG
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db